### ISSUE TITLE
Adding html material objects fails when hit Ctrl F5 in the browser.

### ISSUE THREAD

**Issue by SergiuTalnaci** [fiyazbinhasan/AspNetCoreAngularSPAMaterial#1]
Hi Fiyaz,

I've tried to add a material checkbox to the counter.component.html

<md-checkbox>Check me!</md-checkbox>

WIth HMR the page gets correctly updated and everything works, but if I press CTRL F5 in the browser we get:

Exception: Call to Node module failed with error: Error: Template parse errors:
'md-checkbox' is not a known element:
1. If 'md-checkbox' is an Angular component, then verify that it is part of this module.
2. If 'md-checkbox' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("sed-button class="myButton" (click)="incrementCounter()" [@hoverAnimation]>Increment this</button>

Is there any fix for this?

**Comment by SergiuTalnaci** [comment]
On a side note: 
I fixed it currently by removing the asp-prerender-module attribute in Views/Home/Index.cshtml.

Old:
<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>
New:
<app>Loading...</app>

But now I lost server side rendering SEO

**Comment by fiyazbinhasan** [comment]
Yes. you are on the right track. Problem is Angular Material doesn't fully support `SSR ` right now. But there will be in the future! For the time being remove the `asp-prerender-module` attribute to work with angular material and when they (material team) release fully working version of material that supports `SSR`, re-enable the attribute. :)

**Comment by SergiuTalnaci** [comment]
Thanks 👍  I'll close the issue now :D.
